apiVersion: batch/v1
kind: Job
metadata:
  name: test-requestor-batch-job
spec:
  activeDeadlineSeconds: 600000
  ttlSecondsAfterFinished: 300
  completions: 50
  parallelism: 50
  template:
    metadata:
      name: test-requestor-batch
    spec:
      containers:
      - name: test-requestor
        image: ciscohdz/test-requestor
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 5

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-requestor-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: test-requestor-batch
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24
    ports:
    - protocol: TCP
      port: 8080
