apiVersion: batch/v1
kind: Job
metadata:
  name: test-requestor-batch-job
spec:
  activeDeadlineSeconds: 600000
  completions: 50
  parallelism: 50
  template:
    metadata:
      name: test-requestor-batch
    spec:
      containers:
      - name: test-requestor
        image: ciscohdz/test-requestor
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 5